### ISSUE TITLE
The put test is after delete test in functional testing

### ISSUE THREAD

**Issue by lubodrinka** [freeCodeCamp/boilerplate-project-messageboard#1]
var id;
1.post creating id
2. get. set id
3. del deletete by id
4. put and id doesn't exist
and only output is success.
I am not sure if author want that mean the test not equal success.

**Comment by DaniloNovakovic** [comment]
I think we should upload data manually to the database inside a `beforeAll` or `beforeEach` function in the delete suite to make it work.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
