### ISSUE TITLE
Bug in board.html script

### ISSUE THREAD

**Issue by DaniloNovakovic** [freeCodeCamp/boilerplate-project-messageboard#2]
Hello! I noticed a small bug in board.html in this line:
```
 var currentBoard = window.location.pathname.slice(3, -1);
 var url = "/api/threads/" + currentBoard;
```
currentBoard cuts 1 extra letter which makes GET request invalid, (ex. for `/b/danilosTest` returned would be `danilosTes` instead of `danilosTest` ).

Solution / Fix: `var currentBoard = window.location.pathname.slice(3)`

**Comment by bloo0178** [comment]
This worked for me as well. That is line 35 in board.html from the boilerplate files.

**Comment by iwatakeshi** [comment]
You can also use regex: `window.location.pathname.match(/([^\/]*)\/*$/)[1]`.
This handles the `/` if it's at the end.

Credits: https://stackoverflow.com/a/36741635/1251031

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
