### ISSUE TITLE
board.html and thread.html send report_id instead thread_id

### ISSUE THREAD

**Issue by JROEBKE** [freeCodeCamp/boilerplate-project-messageboard#6]
Should be:
I can report a thread and change its reported value to true by sending a PUT request to /api/threads/{board} and pass along the thread_id. (Text response will be 'success')

But board.html & thread.html have set different name than requirement
`<form id="reportThread"><input type="hidden" name="report_id" value="'+ele._id+'">`
just replace it in two htmls and everything is smooth

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
